# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  - vendor/

stages:
  - test

before_script:
  - npm i -g cordova ionic bower grunt-cli
  - npm i

app:
  script:
    - npm test
  only:
    - feature/gitlab-ci
