language: node_js
node_js:
  - node
  - 5
  - 4
  - 0.12
  - 0.10
cache:
  directories:
    - node_modules
    - vendor
script:
  - npm run test-full
before_script:
  - npm i -g cordova ionic bower grunt-cli
after_success:
  - bash <(curl -s https://codecov.io/bash)
