language: node_js
node_js:
  - node
  - 5
  - 4
  - 0.12
  - 0.10
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - npm i -g cordova ionic bower grunt-cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
